blank_issues_enabled: false
contact_links:
  - name: BreWUi Community Support
    url: https://github.com/AUTOMATIC1111/stable-diffusion-brewui/discussions
    about: Please ask and answer questions here.
